/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:1661c70e-d327-4731-826c-251bfec9c5e8",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_t16FgiWYZ",
    "aws_user_pools_web_client_id": "3c8dqmvevp8fb2s2ldoftrase7",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apif48d1043",
            "endpoint": "https://sx902ped8k.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        },
        {
            "name": "api47cceb23",
            "endpoint": "https://gutq6ep7a7.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        },
        {
            "name": "apida2d6043",
            "endpoint": "https://cwpj9kkfpf.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ]
};


export default awsmobile;
